print("UNC Environment Check")
print("✅ - Pass, ⛔ - Fail,  ⏺️ - No test, ⚠️ - Missing aliases\n\n")

warn("⛔ cache.invalidate")
warn("⛔ cache.iscached")
warn("⛔ cache.replace")
print("✅ cloneref")
print("✅ compareinstances")
warn("⛔ checkcaller")
print("✅ clonefunction")
print("⏺️ getcallingscript")
print("✅ getscriptclosure")
warn("⚠️ getscriptfunction")
print("✅ hookfunction")
warn("⚠️ replaceclosure")
print("✅ iscclosure")
print("✅ islclosure")
warn("⛔ isexecutorclosure")
warn("⚠️ checkclosure, isourclosure")
print("✅ newcclosure")
print("⏺️ rconsoleclear")
warn("⚠️ consoleclear")
print("⏺️ rconsolecreate")
warn("⚠️ consolecreate")
print("⏺️ rconsoledestroy")
warn("⚠️ consoledestroy")
print("⏺️ rconsoleinput")
warn("⚠️ consoleinput")
print("⏺️ rconsoleprint")
warn("⚠️ consoleprint")
print("⏺️ rconsolesettitle")
warn("⚠️ rconsolename, consolesettitle")
print("✅ crypt.base64encode")
print("✅ crypt.base64decode")
print("✅ crypt.encrypt")
print("✅ crypt.decrypt")
print("✅ crypt.generatebytes")
print("✅ crypt.generatekey")
print("✅ crypt.hash")
warn("⛔ debug.getconstant")
warn("⛔ debug.getconstants")
warn("⛔ debug.getinfo")
warn("⛔ debug.getproto")
warn("⛔ debug.getprotos")
warn("⛔ debug.getstack")
warn("⛔ debug.getupvalue")
warn("⛔ debug.getupvalues")
warn("⛔ debug.getconstant")
warn("⛔ debug.setstack")
warn("⛔ debug.setupvalue")
print("✅ readfile")
print("✅ listfiles")
print("✅ writefile")
print("✅ makefolder")
print("✅ appendfile")
print("✅ isfile")
print("✅ isfolder")
print("✅ delfolder")
print("✅ delfile")
print("✅ loadfile")
print("✅ isrbxactive")
print("⏺️ dofile")
print("⏺️ mouse1click")
print("⏺️ mouse1press")
print("⏺️ mouse1release")
print("⏺️ mouse2click")
print("⏺️ mouse2press")
print("⏺️ mouse2release")
print("⏺️ mousemoveabs")
print("⏺️ mousemoverel")
print("⏺️ mousescroll")
warn("⛔ fireclickdetector")
warn("⛔ getcallbackvalue")
warn("⛔ getconnections")
warn("⛔ getcustomasset")
print("✅ gethiddenproperty")
print("✅ sethiddenproperty")
print("✅ gethui")
print("✅ getinstances")
warn("⛔ getnilinstances")
warn("⛔ isscriptable")
warn("⛔ setscriptable")
print("⏺️ setrbxclipboard")
warn("⛔ getrawmetatable")
warn("⛔ hookmetamethod")
warn("⛔ getnamecallmethod")
print("✅ isreadonly")
warn("⛔ setrawmetatable")
warn("⛔ setreadonly")
print("✅ identifyexecutor • Returns version as a string")
print("✅ getexecutorname")
warn("⛔ lz4compress")
warn("⛔ lz4decompress")
print("⏺️ messagebox")
print("⏺️ queue_on_teleport")
warn("⚠️ queueonteleport")
print("⏺️ setclipboard")
warn("⛔ getgc")
print("✅ getgenv")
print("✅ getloadedmodules")
print("✅ getrenv")
warn("⛔ getrunningscripts")
warn("⛔ getscripthash")
print("✅ getscripts")
warn("⛔ getsenv")
print("✅ getthreadidentity")
print("✅ setthreadidentity")
print("⏺️ Drawing")
print("✅ Drawing.new")
print("✅ Drawing.Fonts")
print("✅ isrenderonj")
print("✅ getrenderproperty")
print("✅ setrenderproperty")
warn("⛔ cleardrawcache")
print("⏺️ WebSocket")
warn("⛔ WebSocket.connect")
print("✅ request • User-Agent: Lunar") 
print("✅ loadstring")
print("✅ setfpscap • 60fps @60  • 57fps  @0")
print("\n\n")
print("UNC Summary")
print("✅ Tested with a 56% success rate ("47 out of 83")
print("⛔ 36 tests failed")
print("⚠️ 10 globals are missing aliases")
